# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  [push, pull_request]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./src

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [Win32, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Platform=${{matrix.platform}} /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Package binaries
      if: startsWith(github.ref, 'refs/tags/v')
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path output
        if ("${{ matrix.platform }}" -eq "Win32") {
          Get-ChildItem -Path ${{env.SOLUTION_FILE_PATH}}/${{env.BUILD_CONFIGURATION}} -Recurse -Include *.pdb, *.lib, *.exp, *.ilk, *.bsc | Remove-Item -Force
          Compress-Archive -Path ${{env.SOLUTION_FILE_PATH}}/${{env.BUILD_CONFIGURATION}}/* -DestinationPath output/akelpad-${{ matrix.platform }}.zip
        } else {
          Get-ChildItem -Path ${{env.SOLUTION_FILE_PATH}}/${{ matrix.platform }}/${{env.BUILD_CONFIGURATION}} -Recurse -Include *.pdb, *.lib, *.exp, *.ilk, *.bsc | Remove-Item -Force
          Compress-Archive -Path ${{env.SOLUTION_FILE_PATH}}/${{ matrix.platform }}/${{env.BUILD_CONFIGURATION}}/* -DestinationPath output/akelpad-${{ matrix.platform }}.zip
        }

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: output/*
